export default {
  FONT_SIZE_X_SMALL: 10,
  FONT_SIZE_SMALL: 12,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  FONT_SIZE_X_LARGE: 24,
  FONT_SIZE_XX_LARGE: 28,
  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_NORMAL: '400',
  FONT_WEIGHT_MEDIUM: '600',
  FONT_WEIGHT_HEAVY: '800',
}